server:
  port: 8089

spring:
  profiles:
    active: dev
  config:
    import: "optional:configserver:"
  application:
    name: hyuuny # config-repository? yml ?? -> hyuuny-dev.yml[????????]-[??? ??].yml
  cloud:
    config:
      uri: http://localhost:8088

management:
  endpoints:
    web:
      exposure:
        include: refresh
  endpoint:
    env:
      show-values: ALWAYS

logging:
  level:
    root: info
    web: debug
    org.springframework.cloud: DEBUG

